---

- hosts: localhost
  tasks:
  - name: restart wordpress containers
    shell: "docker-compose --file {{ destination_folder }}/docker-compose.yml restart"  
  vars:
    destination_folder: "{{ wp_location_prefix }}/{{ wp_instance_name }}"
